#!/bin/sh
#
# Resolve all dependencies that the application requires to run.

# The root directory of this resources repo (aka '.')
readonly SOURCE_DIR=$( pwd )

# Ensure we have Homewbrew installed.
if ! [ -x "$(command -v brew)" ]; then
  echo "Homebrew needs to be installed to install Carthage, and other things we depend on."
  exit 0
fi

# Install Homebrew Dependencies such as Carthage.
readonly brew_path=$(echo `which brew`)
echo "==> Updating Homebrew dependencies..."
$($brew_path bundle check)&> /dev/null
if ! [[ $? -eq 0 ]]; then
  $brew_path bundle || exit 1
fi

# Install Ruby gem dependencies.
bundle check --path .bundle >/dev/null 2>&1  || {
  echo "==> Installing gem dependencies..."
  bundle install --path --path .bundle --jobs=4 --retry=3 --quiet || exit 1
}

# Install Yarn Dependencies
echo "==> Bootstrapping Yarn..."
yarn || exit 1

echo "==> Ready to go!"
exit 0
