#!/bin/sh

# script/update: Update application to run for its current checkout.

set -e

bin=$(yarn bin)

eval cd "$(dirname "$0")/.."

eval script/bootstrap

# Set up a local development environment
cd server && $bin/ghost update

echo "==> Dependencies now up-to-date."
