name: Deploy Theme
on:
    push:
        branches:
            - main
        tags:
            - "*"
jobs:
    deploy:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v5
            - name: Deploy Ghost Theme
              uses: TryGhost/action-deploy-theme@v1
              with:
                  api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
                  api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
